apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
      app: manydirections
spec:
  containers:
  - name: redis
    image: kubernetes/redis:v1
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
  volumes:
    - name: data
      emptyDir: {}


